import '../styles/globals.css'
import SideBar from "../Components/SideBar";
import Head from "next/head";
import Footer from "../Components/Footer";
import Authentication from "../Components/Authentication";
import {AuthenticationWrapper} from "../Contexts/Authentication";
import Content from "../Components/Content";

const MyApp = ({Component, pageProps}) => {

    return (
        <>

            <Head>
                <title>Diag+</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="./favicon.png"/>
            </Head>
            <AuthenticationWrapper>
                <div className="flex justify-center py-8 bg-green-300 min-h-screen">
                    <div className="flex basis-10/12 bg-slate-400 text-slate-400 rounded-3xl">

                        <nav className="basis-2/12 text-white pl-4">
                            <SideBar/>
                        </nav>

                        <div className="basis-10/12 bg-white rounded-3xl grid grid-rows-6">

                            <aside className="row-span-1">
                                <Authentication/>
                            </aside>

                            <main className="row-span-4 pl-12 pr-12">
                                <Content Component={Component} pageProps={pageProps}/>
                            </main>

                            <footer className="row-span-1">
                                <Footer/>
                            </footer>
                        </div>

                    </div>

                </div>
            </AuthenticationWrapper>

        </>
    )
}

export default MyApp;
