import '../styles/globals.css'
import SideBar from "../Component/SideBar";
import Head from "next/head";

const MyApp = ({Component, pageProps}) => {
    return (
        <>
            <Head>
                <title>Diag+</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="./favicon.png"/>
            </Head>
            <SideBar/>
            <Component {...pageProps} />
        </>
    )
}

export default MyApp;
