import Head from "next/head";

const Home = () => {
    return (
        <>
            <Head>
                <title>Diag+</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.png"/>
            </Head>
            <h1 className="text-3xl font-bold underline">
                Hello world!
            </h1>
        </>
    )
}

export default Home;
