name: Autodeploy

on:
    push:
        branches: [ main ]

jobs:
    SSH-Connexion:
        
        runs-on: ubuntu-latest
        
        steps:
            - name: Repository checkout
              uses: actions/checkout@v2
            
            - name: SSH connection && main deploy
              uses: appleboy/ssh-action@v0.1.4
              with:
                  host: "diag-plus.tk"
                  username: ${{ secrets.PROD_USER }}
                  key: ${{ secrets.PROD_SSH_KEY }}
                  port: ${{ secrets.PROD_PORT }}
                  script: |
                      cd /var/www/fo-diag-plus
                      git switch main
                      git pull
                      npm install
                      npm run build
                      npm run start
